name: Deploy Product Service to Heroku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: |
        cd product-service
        npm install

    - name: Deploy to Heroku
      run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/product-service-app.git HEAD:master
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
